server:
    image: dockerrepo.eionet.europa.eu:5000/xmlconv
    environment:
        CATALINA_OPTS: |-
            "-Djava.security.egd=file:/dev/./urandom"
            "-Dapp.home=/xmlconv"
            "-Dapp.host=localhost:58080"
            "-Dconfig.log.file=/xmlconv/xmlconv.log"
            "-Dinitial.admin=niknakas,zykaerv,roug"
            "-Dconfig.gdem.url=http://localhost:58080"
            "-Dconfig.dd.url=http://dd.eionet.europa.eu"
            "-Dconfig.dd.rpc.url=http://dd.eionet.europa.eu/rpcrouter"
            "-Dconfig.cr.sparql.endpoint=http://cr.eionet.europa.eu/sparql"
            "-Dconfig.cdr.url=http://cdr.eionet.europa.eu/example"
            "-Dconfig.db.driver=com.mysql.jdbc.Driver"
            "-Dconfig.db.user=test"
            "-Dconfig.db.password=test"
            "-Dconfig.db.jdbcurl=jdbc:mysql://database:3306/xmlconv?autoReconnect=true&characterEncoding=UTF-8&emptyStringsConvertToZero=false&jdbcCompliantTruncation=false"
        JAVA_OPTS: -Xmx3072m
    ports:
        - "58080:8080"
    volumes_from:
        - data_server
    links:
        - database:database
    labels:
          io.rancher.sidekicks: data_server

database:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=xmlconv
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test
    volumes_from:
        - data_db
    labels:
          io.rancher.sidekicks: data_db


data_server:
    image: tianon/true
    volumes:
        - /xmlconv
    labels:
        io.rancher.container.start_once: "true"
        #io.rancher.scheduler.affinity:host_label: hostname=swarm11-eeasites

data_db:
    image: tianon/true
    volumes:
        - /var/lib/mysql
    labels:
        io.rancher.container.start_once: "true"
        #io.rancher.scheduler.affinity:host_label: hostname=swarm11-eeasites

        
